Repository labring/sealos.io, pull requests merged in 2025-03, with the labels that each got.

#12 feat: add mdx file support and configuration
  app/[lang]/legal/index.module.css
  app/[lang]/legal/layout.tsx
  app/[lang]/legal/page.mdx
  mdx-components.tsx
  next.config.mjs
  package-lock.json
  package.json
Labels: size/M

#15 feat: Update DevBox tech grid
  app/[lang]/(home)/devbox/components/techgrid.tsx
  public/icons/astro.svg
  public/icons/debian.svg
  public/icons/nginx.svg
  public/icons/ubuntu.svg
Labels: size/L

#16 chore: Update cta links
  app/[lang]/(home)/components/hero.tsx
  app/[lang]/(home)/devbox/components/footerCta.tsx
  app/[lang]/(home)/devbox/components/hero.tsx
  components/ui/shiny-button.tsx
Labels: size/S

#18 feat: Add blog, update metadata and OpenGraph
  app/[lang]/(home)/components/guides.tsx
  app/[lang]/(home)/components/hero.tsx
  app/[lang]/(home)/devbox/components/hero.tsx
  app/[lang]/(home)/devbox/page.tsx
  app/[lang]/(home)/page.tsx
  app/[lang]/blog/[slug]/layout.tsx
  app/[lang]/blog/[slug]/page.tsx
  app/[lang]/blog/blog.module.css
  app/[lang]/blog/layout.tsx
  app/[lang]/blog/page.tsx
  app/[lang]/docs/[[...slug]]/page.tsx
  app/api/og/[type]/[title]/route.ts
  app/layout.config.tsx
  app/layout.tsx
  components/header/hero.tsx
  config/site.ts
  kafka.svg
  lib/utils/metadata.ts
  milvus.svg
  package-lock.json
  package.json
  public/images/og/default.jpeg
  public/images/og/icons/blog.svg
  public/images/og/icons/docs.svg
  public/sealos-full.svg
  public/sealos.svg
  redis.svg
  source.config.ts
Labels: size/XXL

#19 feat: Add blog categories
  app/[lang]/(home)/blog/[slug]/layout.tsx
  app/[lang]/(home)/blog/page.tsx
  app/[lang]/(home)/components/guides.tsx
  app/[lang]/(home)/components/hero.tsx
  app/[lang]/(home)/devbox/components/hero.tsx
  app/[lang]/(home)/devbox/page.tsx
  app/[lang]/(home)/page.tsx
  app/[lang]/blog/[slug]/layout.tsx
  app/[lang]/blog/[slug]/page.tsx
  app/[lang]/blog/blog.module.css
  app/[lang]/blog/category/[category]/page.tsx
  app/[lang]/blog/category/page.tsx
  app/[lang]/blog/components/BlogHeader.tsx
  app/[lang]/blog/components/BlogItem.tsx
  app/[lang]/blog/components/CategoryBar.tsx
  app/[lang]/blog/layout.tsx
  app/[lang]/blog/page.tsx
  app/[lang]/docs/[[...slug]]/page.tsx
  app/api/og/[type]/[title]/route.ts
  app/global.css
  app/layout.config.tsx
  app/layout.tsx
  components/header/hero.tsx
  config/site.ts
  content/docs/index.mdx
  kafka.svg
  lib/utils/blog-utils.ts
  lib/utils/metadata.ts
  milvus.svg
  package-lock.json
  package.json
  public/images/og/default.jpeg
  public/images/og/icons/blog.svg
  public/images/og/icons/docs.svg
  public/sealos-full.svg
  public/sealos.svg
  redis.svg
  source.config.ts
  tsconfig.json
Labels: size/XL

#24 chore: Fix font render on serverless
  app/api/og/[type]/[title]/route.ts
  public/fonts/arial-bold.otf
  public/fonts/arial.otf
Labels: size/M

#25 chore: Fix font includes for Vercel
  app/api/og/[type]/[title]/route.ts
  fonts/arial-bold.ttf
  fonts/arial.ttf
  vercel.json
Labels: size/L

#17 feat: prompt version change for Chinese IP users
  app/[lang]/(home)/page.tsx
  components/redirectSuggest.tsx
Labels: size/L

#26 chore: Update blog and docs config
  app/[lang]/(home)/components/guides.tsx
  app/[lang]/(home)/devbox/components/footerCta.tsx
  app/[lang]/(home)/devbox/components/techgrid.tsx
  app/[lang]/(home)/devbox/page.tsx
  app/[lang]/(home)/page.tsx
  app/[lang]/blog/[slug]/layout.tsx
  app/layout.config.tsx
  components/docs/Links.tsx
  components/footer/index.tsx
  components/header/index.tsx
  components/ui/shiny-button.tsx
  config/site.ts
  content/blog/(what-is)/what-is-sealos/index.md
  content/docs/guides/app-launchpad/add-a-domain.mdx
  content/docs/guides/app-launchpad/autoscaling.mdx
  content/docs/guides/app-launchpad/configmap.mdx
  content/docs/guides/app-launchpad/environments.mdx
  content/docs/guides/app-launchpad/expose-multiple-ports.mdx
  content/docs/guides/app-launchpad/persistent-volume.mdx
  content/docs/guides/app-launchpad/update-apps.mdx
  content/docs/guides/fundamentals/create-a-project.mdx
  content/docs/guides/fundamentals/deploy.mdx
  content/docs/guides/fundamentals/develop.mdx
  content/docs/index.mdx
  content/docs/quick-start.mdx
Labels: size/L

#27 Update Dockerfile
  Dockerfile
Labels: size/S

#29 feat: remove @tailwindcss/typography to resolve style conflict
  README.md
  app/[lang]/legal/index.module.css
  app/[lang]/legal/layout.tsx
  app/global.css
  config/site.ts
  package.json
  tailwind.config.js
Labels: size/L

#30 typo: fix repo name
  app/[lang]/docs/[[...slug]]/page.tsx
  app/[lang]/layout.tsx
Labels: size/XS

#31 docs: Add entrypoint.sh guide
  content/docs/guides/fundamentals/entrypoint-sh.mdx
  content/docs/guides/fundamentals/meta.json
Labels: size/L

#32 feat: add i18n & TOC in blog page
  app/[lang]/(home)/devbox/page.tsx
  app/[lang]/(home)/page.tsx
  app/[lang]/blog/[slug]/layout.tsx
  app/[lang]/blog/[slug]/page.tsx
  app/[lang]/blog/blog.module.css
  app/[lang]/blog/page.tsx
  app/[lang]/legal/index.module.css
  app/[lang]/legal/layout.tsx
  app/global.css
  components/footer/index.tsx
  components/header/index.tsx
  content/blog/(what-is)/what-is-sealos/index.zh-cn.md
Labels: size/XL

#37 blog: New article
  content/blog/(what-is)/what-is-kubernetes/index.md
Labels: size/L

#35 docs: Update docs
  content/docs/k8s/quick-start/install-cli.zh-cn.mdx
Labels: size/XS

#36 chore: FIx blog title images
  app/[lang]/blog/[slug]/layout.tsx
  app/[lang]/blog/components/BlogItem.tsx
  lib/utils/blog-utils.ts
Labels: size/XS

#40 fix: improve blog post language filtering by file path
  app/[lang]/blog/category/[category]/page.tsx
  app/[lang]/blog/page.tsx
  lib/utils/blog-utils.ts
Labels: size/M

#41 chore: Fix responsive styling on blog
  app/[lang]/blog/[slug]/layout.tsx
Labels: size/S

#42 blog: New article
  content/blog/(what-is)/what-is-devbox/index.md
Labels: size/L

#43 blog: New Article
  components/ui/button.tsx
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-console.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-console.zh-cn.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-console2.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-details.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-details.zh-cn.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-logs.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-on-sealos.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-on-sealos.zh-cn.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-on-sealos2.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-on-sealos2.zh-cn.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-text-mode-command.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-text-mode.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-text-mode.zh-cn.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-whiteboard-mode-template.webp
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-whiteboard-mode-template.zh-cn.webp
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-whiteboard-mode.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-whiteboard-mode.zh-cn.jpg
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-whiteboard.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE-workspace.png
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/images/AFFINE.jpg
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/index.mdx
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/index.zh-cn.mdx
  content/blog/(what-is)/what-is-kubernetes/index.zh-cn.md
  content/blog/(what-is)/what-is-sealos/index.zh-cn.md
Labels: size/XL

#46 fix: improve SEO and web crawling configurations
  app/api/robots/route.ts
  app/sitemap.ts
  middleware.ts
Labels: size/S

#45 blog: New article
  content/blog/(best-practices)/the-ultimate-guide-to-making-ai-games/images/board_game.webp
  content/blog/(best-practices)/the-ultimate-guide-to-making-ai-games/images/educational_game.webp
  content/blog/(best-practices)/the-ultimate-guide-to-making-ai-games/images/game.webp
  content/blog/(best-practices)/the-ultimate-guide-to-making-ai-games/images/ide.webp
  content/blog/(best-practices)/the-ultimate-guide-to-making-ai-games/images/play_together.webp
  content/blog/(best-practices)/the-ultimate-guide-to-making-ai-games/images/project_management.webp
  content/blog/(best-practices)/the-ultimate-guide-to-making-ai-games/index.md
Labels: size/L

#47 feat: update CI workflow and domain references
  .github/workflows/build-image.yml
  config/site.ts
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/index.mdx
Labels: size/M

#49 fix: include git history for last modified timestamps
  .dockerignore
  .github/workflows/build-image.yml
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
Labels: size/S

#48 feat: Add i18n in navbar
  app/[lang]/(home)/devbox/page.tsx
  app/[lang]/(home)/page.tsx
  app/[lang]/legal/layout.tsx
  app/layout.config.tsx
  components/header/index.tsx
Labels: size/L

#50 Upgrade Vercel deployment workflows with CLI integration
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
Labels: size/S

#51 chore: delete pnpm-lock.yaml
  .github/workflows/preview.yml
  pnpm-lock.yaml
Labels: size/XS

#54 refactor: update Vercel deployment workflow and add jest-worker dependency
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  package-lock.json
  package.json
Labels: size/S

#53 fix: abnormal pre&next page in `blog`
  .gitignore
  app/[lang]/blog/[slug]/layout.tsx
  lib/utils/blog-utils.ts
Labels: size/M

#52 feat: Optimize blog images
  Dockerfile
  app/api/og/init-blog/route.ts
  lib/utils/blog-utils.ts
Labels: size/S

#61 chore: Bump Vercel version
  .github/workflows/preview.yml
Labels: size/XS

#63 doc: add sdk code to object-storage.zh-cn.mdx
  content/docs/guides/object-storage.zh-cn.mdx
Labels: size/L

#64 fix: add graphics dependencies for image generation in Docker build
  .github/workflows/preview.yml
  Dockerfile
  content/blog/(app-deployment)/how-to-deploy-and-configure-flarum-using-docker/index.mdx
Labels: size/S
