Repository labring/sealos.io, pull requests merged in 2025-06, with the labels that each got.

#111 feat: Pricing page
  app/[lang]/(home)/pricing/components/feature-card.tsx
  app/[lang]/(home)/pricing/components/get-started.tsx
  app/[lang]/(home)/pricing/components/pricing-table.tsx
  app/[lang]/(home)/pricing/page.tsx
  app/layout.config.tsx
  components/footer/index.tsx
  config/pricing.ts
  vercel.json
Labels: size/XL

#113 blog: Update Article
  content/blog/(best-practices)/sealos-higress-ingress-performance-optimization-minute-to-second/images/sealos-envoy-flamegraph-optimized-data-plane.png
  content/blog/(best-practices)/sealos-higress-ingress-performance-optimization-minute-to-second/images/sealos-istio-flamegraph-optimized-controller.png
  content/blog/(best-practices)/sealos-higress-ingress-performance-optimization-minute-to-second/index.zh-cn.md
Labels: size/S

#115 feat: Support rss
  app/[lang]/blog/components/BlogHeader.tsx
  app/rss.xml/route.ts
  components/footer/index.tsx
  components/ui/icons.tsx
  components/ui/rss-button.tsx
  content/blog/(app-deployment)/how-to-deploy-affine-open-source-notion-alternative/index.en.mdx
  content/blog/(app-deployment)/how-to-deploy-and-configure-flarum-using-docker/index.en.mdx
  content/blog/(app-deployment)/how-to-deploy-and-configure-meilisearch-using-docker/index.en.mdx
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/index.en.mdx
  content/blog/(best-practices)/cursor-free-for-students/index.en.md
  content/blog/(best-practices)/funding-open-source/index.en.md
  content/blog/(best-practices)/sealos-for-education/index.en.md
  content/blog/(best-practices)/the-ultimate-guide-to-making-ai-games/index.en.md
  content/blog/(tech-compared)/kubernetes-vs-docker/index.en.md
  content/blog/(tech-compared)/top-ai-code-editors/index.en.md
  content/blog/(what-is)/what-is-cloud-native/index.en.md
  content/blog/(what-is)/what-is-devbox/index.en.md
  content/blog/(what-is)/what-is-docker/index.en.md
  content/blog/(what-is)/what-is-kafka/index.en.md
  content/blog/(what-is)/what-is-kubernetes/index.en.md
  content/blog/(what-is)/what-is-mcp/index.en.md
  content/blog/(what-is)/what-is-microvm/index.en.md
  content/blog/(what-is)/what-is-milvus/index.en.md
  content/blog/(what-is)/what-is-mongodb/index.en.md
  content/blog/(what-is)/what-is-mysql/index.en.md
  content/blog/(what-is)/what-is-postgresql/index.en.md
  content/blog/(what-is)/what-is-redis/index.en.md
  content/blog/(what-is)/what-is-sealos/index.en.md
  content/blog/(what-is)/what-is-vibe-coding/index.en.md
  lib/utils/metadata.ts
  middleware.ts
  package-lock.json
  package.json
Labels: size/L

#119 blog: Update article
  content/blog/(best-practices)/sealos-envoy-vs-nginx-2000-tenants/index.en.md
  content/blog/(best-practices)/sealos-envoy-vs-nginx-2000-tenants/index.zh-cn.md
Labels: size/S

#122 feat: Update app script and apps
  config/apps.json
  config/apps.ts
  public/images/apps/featbit-standard.png
  public/images/apps/jsoncrack.png
  scripts/generate-apps.js
Labels: size/XXL

#127 fix(seo): add i18n support to product page metadata
  app/[lang]/products/app-store/[slug]/page.tsx
  app/[lang]/products/app-store/page.tsx
  app/[lang]/products/databases/page.tsx
Labels: size/M

#128 feat: enable static site generation for documentation pages
  app/[lang]/layout.tsx
  next.config.mjs
Labels: size/S

#130 chore: Update get started button
  components/header/index.tsx
  components/ui/shiny-button.tsx
  lib/gtm.ts
Labels: size/XS

#131 chore: Optimize case page
  app/[lang]/customers/components/case-card.tsx
  app/[lang]/customers/components/case-grid.tsx
  app/[lang]/customers/components/empty-state.tsx
  app/[lang]/customers/components/filter-button.tsx
  app/[lang]/customers/components/filter-section.tsx
  app/[lang]/customers/config/case-translations.ts
  app/[lang]/customers/hooks/use-case-filter.ts
  content/docs/k8s/lifecycle-management.zh-cn.mdx
  content/docs/k8s/reference/sealos/commands/registry.zh-cn.mdx
Labels: size/XL

#107 blog: New article
  content/blog/(app-deployment)/how-to-deploy-tolgee/images/integrations.webp
  content/blog/(app-deployment)/how-to-deploy-tolgee/images/languages-mt-settings.webp
  content/blog/(app-deployment)/how-to-deploy-tolgee/images/organization-member-permissions.webp
  content/blog/(app-deployment)/how-to-deploy-tolgee/images/project-settings.webp
  content/blog/(app-deployment)/how-to-deploy-tolgee/images/translations_view.webp
  content/blog/(app-deployment)/how-to-deploy-tolgee/index.en.md
Labels: size/L

#133 feat: optimize case study page layout and fix TOC positioning issues
  app/[lang]/customers/[slug]/page.tsx
  app/[lang]/customers/components/toc-sidebar.tsx
Labels: size/XL

#134 feat: improve TypeScript type safety across components
  app/[lang]/(home)/components/marquee.tsx
  app/[lang]/blog/[slug]/page.tsx
  app/[lang]/customers/[slug]/page.tsx
  components/ui/animated-grid-pattern.tsx
  components/ui/animated-tooltip.tsx
  components/ui/sticky-scroll-reveal.tsx
  lib/utils/structured-data.ts
Labels: size/M

#137 blog: New articles
  content/blog/(tech-compared)/public-cloud-vs-private-cloud/index.en.md
  content/blog/(what-is)/what-is-cloud-computing/index.en.md
  content/blog/(what-is)/what-is-hybrid-cloud/index.en.md
  content/blog/(what-is)/what-is-multi-cloud/index.en.md
Labels: size/XXL

#138 docs: Support MCP
  app/[lang]/(home)/page.tsx
  app/[lang]/products/app-store/page.tsx
  content/docs/AI/mcp.mdx
  content/docs/AI/mcp.zh-cn.mdx
  content/docs/meta.zh-cn.json
Labels: size/XL

#141 perf: optimize React components with memo, useMemo, and useCallback
  app/[lang]/(home)/components/feature-grid/integrations.tsx
  app/[lang]/products/app-store/components/applications.tsx
  components/header/index.tsx
  components/ui/sticky-scroll-reveal.tsx
Labels: size/L

#144 perf: optimize lazy loading and image performance
  app/[lang]/(home)/components/why-choose-us.tsx
  app/[lang]/customers/[slug]/page.tsx
  app/[lang]/customers/components/hero.tsx
  app/[lang]/customers/components/trusted-companies.tsx
  app/[lang]/products/app-store/[slug]/components/Screenshots.tsx
  app/[lang]/products/devbox/components/feature.tsx
  app/[lang]/products/devbox/components/techgrid.tsx
  components/ui/app-icon.tsx
  components/ui/button.tsx
  next.config.mjs
Labels: size/L

#147 chore: Mobile optimizations
  app/[lang]/(home)/components/why-choose-us.tsx
  app/[lang]/layout.tsx
  components/footer/index.tsx
  components/redirectSuggest.tsx
  components/ui/call-to-action-section.tsx
  next.config.mjs
Labels: size/L
