Repository labring/sealos.io, pull requests merged in 2025-05, with the labels that each got.

#89 blog: New articles
  content/blog/(what-is)/what-is-microvm/index.md
  content/blog/(what-is)/what-is-postgresql/index.md
Labels: size/L

#90 chore: Fix blog article location
  content/blog/(what-is)/what-is-microvm/index.md
  content/blog/(what-is)/what-is-postgresql/index.md
Labels: size/XL

#92 feat(analytics): add Rybbit analytics with lazy loading
  components/analytics/index.tsx
  config/analytics.ts
Labels: size/M

#95 Update vercel.json
  middleware.ts
  vercel.json
Labels: size/M

#94 docs: fix registryPort field description
  content/docs/k8s/advanced-guide/image-build-standardized.zh-cn.mdx
Labels: size/XS

#93 blog: Update article
  content/blog/(what-is)/what-is-devbox/index.md
Labels: size/L

#96 feat: Add analytics custom event
  app/[lang]/(home)/devbox/page.tsx
  components/ui/shiny-button.tsx
  types/rybbit.d.ts
Labels: size/S

#99 blog: New articles
  content/blog/(best-practices)/cursor-free-for-students/images/cursor.webp
  content/blog/(best-practices)/cursor-free-for-students/index.md
  content/blog/(what-is)/what-is-cloud-native/index.md
Labels: size/L

#100 feat: Education landing page
  app/[lang]/(home)/education/components/faq.tsx
  app/[lang]/(home)/education/components/feature.tsx
  app/[lang]/(home)/education/page.tsx
  components/footer/index.tsx
  components/header/hero.tsx
Labels: size/L

#98 feat: enhance landing page with animated components and improved layouts
  app/[lang]/(home)/components/faq.tsx
  app/[lang]/(home)/components/feature-grid.tsx
  app/[lang]/(home)/components/marquee.tsx
  app/[lang]/(home)/components/trusted.tsx
  app/[lang]/(home)/components/why-choose-us.tsx
  app/[lang]/(home)/devbox/page.tsx
  app/[lang]/(home)/page.tsx
  app/global.css
  app/layout.config.tsx
  components/footer/index.tsx
  components/header/hero.tsx
  components/scroll-progress-wrapper.tsx
  components/ui/accordion.tsx
  components/ui/animated-wrapper.tsx
  components/ui/counter.tsx
  components/ui/scroll-indicator.tsx
  components/ui/testimonial-badge.tsx
  components/video.tsx
  package-lock.json
  package.json
Labels: size/XXL

#101 blog: New article
  content/blog/(what-is)/what-is-vibe-coding/index.md
Labels: size/L

#103 Update gen-apply-cluster
  content/docs/k8s/operations/run-cluster/gen-apply-cluster.zh-cn.mdx
Labels: size/XS

#106 blog: New articles
  content/blog/(what-is)/what-is-milvus/index.md
  content/blog/(what-is)/what-is-redis/index.md
Labels: size/XL

#108 Update docs
  content/docs/guides/databases/redis/nodejs.mdx
Labels: size/XXL

#109 blog: New articles
  content/blog/(what-is)/what-is-kafka/images/kafka-architecture.webp
  content/blog/(what-is)/what-is-kafka/index.md
  content/blog/(what-is)/what-is-mongodb/images/mongodb-architecture.webp
  content/blog/(what-is)/what-is-mongodb/index.md
  content/blog/(what-is)/what-is-mysql/images/mysql-architecture.webp
  content/blog/(what-is)/what-is-mysql/index.md
Labels: size/XXL
