Repository labring/sealos.io, pull requests merged in 2025-08, with the labels that each got.

#171 Blog: new article
  content/blog/(best-practices)/local-to-cloud-development-migration-sealos-devbox/images/sealos-devbox-database-credentials.png
  content/blog/(best-practices)/local-to-cloud-development-migration-sealos-devbox/index.en.md
  content/blog/(best-practices)/local-to-cloud-development-migration-sealos-devbox/index.zh-cn.md
Labels: size/XL

#173 blog: New articles
  content/blog/(best-practices)/a-guide-for-beginners/index.en.md
  content/blog/(best-practices)/cursor-devbox/index.en.md
  content/blog/(best-practices)/how-sealos-devbox-accelerates-agile-development/index.en.md
  content/blog/(best-practices)/how-sealos-devbox-supercharges-student-development/index.en.md
  content/blog/(best-practices)/how-sealos-devbox-transforms-enterprise-development-workflows/index.en.md
  content/blog/(best-practices)/local-to-cloud-development-migration-sealos-devbox/index.en.md
  content/blog/(best-practices)/sealos-high-availability-by-default/index.en.md
  content/blog/(best-practices)/trae-devbox/index.en.md
  content/blog/(best-practices)/vscode-devbox/index.en.md
  content/blog/(best-practices)/windsurf-devbox/index.en.md
  content/blog/(best-practices)/zed-devbox/index.en.md
  content/blog/(tech-compared)/devbox-vs-codespaces/index.en.md
  content/blog/(tech-compared)/the-sealos-security-path/index.en.md
Labels: size/XXL

#172 Blog: new article
  content/blog/(best-practices)/sealos-devbox-commit-performance-optimization/images/devbox-commit-performance-flame-graph-after-optimization.png
  content/blog/(best-practices)/sealos-devbox-commit-performance-optimization/images/devbox-commit-performance-flame-graph-before-optimization.png
  content/blog/(best-practices)/sealos-devbox-commit-performance-optimization/index.en.md
  content/blog/(best-practices)/sealos-devbox-commit-performance-optimization/index.zh-cn.md
Labels: size/XL

#174 chore: Update configs
  app/[lang]/layout.tsx
  components/analytics/index.tsx
  content/blog/(best-practices)/windsurf-devbox/index.en.md
Labels: size/M

#177 docs: Update Sealos version compatibility for Kubernetes v1.30.0
  content/docs/k8s/quick-start/deploy-kubernetes.zh-cn.mdx
Labels: size/XS
