Repository labring/sealos.io, pull requests merged in 2025-07, with the labels that each got.

#151 blog: New articles
  content/blog/(app-store-choices)/google-analytics-alternative/images/matomo.webp
  content/blog/(app-store-choices)/google-analytics-alternative/images/plausible.webp
  content/blog/(app-store-choices)/google-analytics-alternative/images/rybbit.webp
  content/blog/(app-store-choices)/google-analytics-alternative/images/umami.webp
  content/blog/(app-store-choices)/google-analytics-alternative/index.en.md
  content/blog/(app-store-choices)/open-source-marketing-toolkit/index.en.md
  content/blog/(what-is)/what-is-a-cloud-opearting-system/index.en.md
  content/blog/(what-is)/what-is-cloud-development-environment/index.en.md
  content/blog/(what-is)/what-is-yaml/index.en.md
Labels: size/XL

#152 docs: Update zh docs
  content/docs/guides/app-launchpad/meta.zh-cn.json
  content/docs/guides/fundamentals/index.zh-cn.mdx
  content/docs/guides/fundamentals/meta.zh-cn.json
  content/docs/guides/meta.zh-cn.json
  content/docs/meta.zh-cn.json
  content/docs/overview/intro.zh-cn.mdx
  content/docs/quick-start.zh-cn.mdx
Labels: size/L

#157 chore: FIx homepage OG
  app/[lang]/(home)/page.tsx
Labels: size/XS

#162 feat: enhance DevBox SEO with improved structured data
  app/[lang]/products/devbox/page.tsx
  lib/utils/structured-data.ts
  public/favicon/site.webmanifest
Labels: size/M
