Repository labring/sealos.io, pull requests merged in 2025-04, with the labels that each got.

#65 Enhance sitemap with localization and expanded content
  app/sitemap.ts
Labels: size/M

#66 feat(i18n): implement footer and CTA internationalization
  app/[lang]/(home)/devbox/page.tsx
  app/[lang]/(home)/page.tsx
  app/[lang]/blog/[slug]/layout.tsx
  app/[lang]/blog/layout.tsx
  app/[lang]/legal/layout.tsx
  components/footer/index.tsx
  components/ui/icons.tsx
  config/site.ts
  types/index.d.ts
Labels: size/L

#67 Update DevBox copy
  app/[lang]/(home)/devbox/components/featurefour.tsx
  app/[lang]/(home)/devbox/page.tsx
Labels: size/S

#69 blog: New article
  content/blog/(what-is)/what-is-devbox/index.md
  content/blog/(what-is)/what-is-docker/index.md
  content/blog/(what-is)/what-is-mcp/index.md
  content/blog/(what-is)/what-is-sealos/index.md
Labels: size/L

#70 chore: Update CTA
  components/header/hero.tsx
Labels: size/XS

#72 blog: New article
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/images/cherry-studio-screenshot.jpg
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/images/create-mcp-devbox.png
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/images/open-devbox-in-ide.png
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/images/publish-devbox.png
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/images/run-devbox.png
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/index.md
Labels: size/L

#73 feat: Optional custom image titles for blog
  app/[lang]/blog/[slug]/layout.tsx
  app/[lang]/blog/components/BlogItem.tsx
  app/api/og/init-blog/route.ts
  content/blog/(app-deployment)/how-to-deploy-and-configure-flarum-using-docker/index.mdx
  content/blog/(app-deployment)/how-to-deploy-and-configure-meilisearch-using-docker/index.mdx
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/index.md
  content/blog/(what-is)/what-is-mcp/index.md
  lib/utils/metadata.ts
  source.config.ts
Labels: size/S

#71 feat: upgrade to fumadocs-core@15.2.6 tailwindcss@4.1.3
  app/[lang]/(home)/components/feature-grid/bentogrid.tsx
  app/[lang]/(home)/components/feature-grid/integrations.tsx
  app/[lang]/(home)/components/feature-grid/integrations/tiles.tsx
  app/[lang]/(home)/components/feature-grid/logocluster.tsx
  app/[lang]/(home)/components/guides.tsx
  app/[lang]/(home)/components/marquee.tsx
  app/[lang]/(home)/devbox/components/deployButton.tsx
  app/[lang]/blog/[slug]/layout.tsx
  app/global.css
  app/layout.config.tsx
  components/featurefour.tsx
  components/header/hero.tsx
  components/header/index.tsx
  components/ui/animated-tooltip.tsx
  components/ui/button.tsx
  components/ui/shiny-button.tsx
  components/ui/sticky-scroll-reveal.tsx
  components/ui/text.tsx
  components/ui/typing-animation.tsx
  components/video.tsx
  content/docs/community.zh-cn.mdx
  content/docs/examples/build-your-own-discord-bot.mdx
  content/docs/examples/build-your-own-discord-bot.zh-cn.mdx
  content/docs/k8s/quick-start/build-ingress-cluster-image.zh-cn.mdx
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
Labels: size/XL

#74 fix: blog miss
  content/docs/examples/meta.zh-cn.json
  lib/utils/blog-utils.ts
Labels: size/S

#75 docs: update docs
  content/docs/community.zh-cn.mdx
  content/docs/examples/meta.zh-cn.json
  content/docs/guides/databases/kafka/meta.zh-cn.json
  content/docs/guides/databases/milvus/meta.zh-cn.json
  content/docs/guides/databases/mongodb/meta.zh-cn.json
  content/docs/guides/databases/mysql/meta.zh-cn.json
  content/docs/guides/databases/postgresql/meta.zh-cn.json
  content/docs/guides/databases/redis/meta.zh-cn.json
  content/docs/k8s/reference/sealctl/meta.json
  content/docs/k8s/reference/sealctl/meta.zh-cn.json
  content/docs/k8s/reference/sealctl/tar-and-untar.mdx
  content/docs/k8s/reference/sealctl/tar-and-untar.zh-cn.mdx
  content/docs/k8s/reference/sealos/commands/meta.json
  content/docs/k8s/reference/sealos/commands/meta.zh-cn.json
  content/docs/msa/meta.zh-cn.json
  next.config.mjs
Labels: size/M

#76 feature: add llms.txt
  app/llms.txt/route.ts
  middleware.ts
  package-lock.json
  package.json
Labels: size/M

#77 add Deploy-on-Sealos.svg
  middleware.ts
  public/Deploy-on-Sealos.svg
Labels: size/S

#78 feat: Add YouTube video support
  components/docs/Video.tsx
  content/blog/(app-deployment)/how-to-deploy-your-own-mcp-server/index.mdx
  lib/og-canvas.ts
  public/images/og/icons/video.svg
Labels: size/L

#80 feat: Improved language support
  app/[lang]/blog/[slug]/layout.tsx
  app/[lang]/docs/layout.tsx
  app/[lang]/layout.tsx
  app/layout.config.tsx
  app/layout.tsx
  lib/i18n.ts
  lib/utils/blog-utils.ts
Labels: size/L

#82 feat: add localized banner with styled CTA button to docs
  app/[lang]/docs/layout.tsx
  app/components/banner-button.module.css
Labels: size/M

#83 blog: New article
  content/blog/(tech-compared)/kubernetes-vs-docker/index.md
Labels: size/L

#84 feat: Add cases landing page
  app/[lang]/customers/[slug]/layout.tsx
  app/[lang]/customers/[slug]/page.tsx
  app/[lang]/customers/components/call-to-action.tsx
  app/[lang]/customers/components/case-grid.tsx
  app/[lang]/customers/components/case-wrapper.tsx
  app/[lang]/customers/components/featured-cases.tsx
  app/[lang]/customers/components/hero.tsx
  app/[lang]/customers/components/testimonials.tsx
  app/[lang]/customers/components/trusted-companies.tsx
  app/[lang]/customers/layout.tsx
  app/[lang]/customers/page.tsx
  app/layout.config.tsx
  components/footer/index.tsx
  lib/og-canvas.ts
  lib/utils/metadata.ts
  middleware.ts
  package-lock.json
  package.json
  public/images/customers/617d9094488a36d3512669b0980f4541.png?_286x76.png
  public/images/customers/aijia.png
  public/images/customers/beiyou.png
  public/images/customers/bg-pattern.png
  public/images/customers/case-banner.jpeg
  public/images/customers/case-banner.png
  public/images/customers/case-study-hero.jpg
  public/images/customers/cncdrives.png
  public/images/customers/hero-illustration.svg
  public/images/customers/hkust.svg
  public/images/customers/igettool.png
  public/images/customers/infra-costs-chart.jpg
  public/images/customers/inspur.svg
  public/images/customers/jbufa.png
  public/images/customers/kenuoer.png
  public/images/customers/knorr-bremse.svg
  public/images/customers/quanyaowuliu.jpg
  public/images/customers/results-chart.jpg
  public/images/customers/sinocare.png
  public/images/customers/sinocare/sealos-cloud-operating-system-platform.png
  public/images/customers/sinocare/sinocare-company-headquarters.jpeg
  public/images/customers/sinocare/sinocare-fastgpt-ai-customer-service-workflow.png
  public/images/customers/sinocare/sinocare-sealos-fastgpt-tech-stack-architecture.png
  public/images/customers/solution-architecture.jpg
  public/images/customers/teable.png
  public/images/customers/teable.svg
  public/images/customers/teable.webp
  public/images/customers/teable/sealos-app-store-interface.png
  public/images/customers/teable/sealos-get-kubeconfig-file.png
  public/images/customers/teable/sealos-preview-environment-yaml-template.png
  public/images/customers/teable/sealos-teable-one-click-deployment.png
  public/images/customers/teable/teable-architecture-design-diagram.png
  public/images/customers/teable/teable-github-actions-cd-workflow-code.png
  public/images/customers/teable/teable-no-code-database-platform-overview.png
  public/images/customers/teable/teable-runa-capital-oss-index-q2-2024.png
  public/images/customers/wuhandaxue.png
  public/images/customers/zsmarter.png
Labels: size/XXL

#85 Improve customer case page scrolling discoverability
  app/[lang]/customers/components/featured-cases.tsx
  app/[lang]/customers/components/hero.tsx
  app/[lang]/customers/page.tsx
Labels: size/S

#86 blog: New article
  content/blog/(tech-compared)/top-ai-code-editors/images/cursor.webp
  content/blog/(tech-compared)/top-ai-code-editors/images/trae.webp
  content/blog/(tech-compared)/top-ai-code-editors/images/vscode.webp
  content/blog/(tech-compared)/top-ai-code-editors/images/windsurf.webp
  content/blog/(tech-compared)/top-ai-code-editors/index.md
Labels: size/L
